server:
  port: 6003
spring:
  # Rabbitmq配置
  rabbitmq:
    cache:
      channel:
        checkout-timeout: 1s
    host: localhost
    port: 5672
    username: root
    password: 123456
demoname: demodemomodel